gophermart
Matthew3000/gophermart pull request #1
Opened 2022-10-15 14:02 UTC by Matthew3000

2022-10-23 10:59 UTC, kilchik requested changes

2022-10-23 10:59 UTC, kilchik commented on internal/app/handlers.go
> +		} else {
else не нужен

2022-10-23 10:59 UTC, kilchik commented on internal/storage/acces_db.go
> +	dbStorage.db.Create(&user)
Мы не можем игнорировать ошибки от базы данных. Так здесь может возникнуть ошибка о дубликате ключа (между вызовами dbStorage.db.Where и dbStorage.db.Create мог вставиться тот же пользователь). Ошибки от БД могут быть самыми разными, и каждую ошибку нужно корректно обработать.
gorm предлагает использовать атрибут Error для отслеживания ошибок.

2022-10-23 10:59 UTC, kilchik commented on internal/storage/acces_db.go
> +	dbStorage.db.Where("login = ?", user.Login).First(&dbUser)
Сейчас все походы в базу делаются без context. Без context мы не можем лимитировать время работы хэндлера, не можем корректно завершить его работу при обрыве клиентского соединения. Необходимо все вызовы к gorm снабдить контекстом, пробрасываемым из хэндлеров https://gorm.io/docs/context.html

2022-10-23 10:59 UTC, kilchik commented on internal/storage/acces_db.go
> +	dbStorage.db.Where("status = ?", "NEW").Or("status = ?", "REGISTERED").
Статусы и прочие строковые константы (особенно повторяющиеся) необходимо выносить в константы

2022-10-23 10:59 UTC, kilchik commented on internal/storage/acces_db.go
> +				time.Sleep(10 * time.Second)
Это очень неочевидное поведение от метода для вставки в базу: 
- обращение к сервису по расчету баллов логически не должно происходить в рамках метода DBStorage
- sleep стоит вынести в константу и вместе с походом в сервис расчета баллов вынести из UpdateAccrual

2022-10-23 10:59 UTC, kilchik commented on internal/storage/acces_db.go
> +		req := resty.New().
Я бы предложил добавить таймаут на поход в сторонний сервис

2022-10-23 10:59 UTC, kilchik commented on internal/app/handlers.go
> +		err = app.userStorage.SetBalanceByLogin(withdrawal.Login, newBalance)
Представь, что от клиента приходят одновременно несколько запросов на списание баллов. Если не пользоваться транзакциями и не блокировать баланс на изменение, то результат может выглядеть вот так
<img width="921" alt="image" src="https://user-images.githubusercontent.com/20778913/197388292-cffed588-c9c2-4559-874d-f9409b311c82.png">

2022-10-24 10:16 UTC, Matthew3000 commented on internal/app/handlers.go
> +		err = app.userStorage.SetBalanceByLogin(withdrawal.Login, newBalance)
Добавить мьютексы?

2022-11-01 20:44 UTC, kilchik approved these changes

2022-11-01 20:44 UTC, kilchik commented on internal/app/update_accural.go
> +					return err
Недостаточно просто возвращать err, когда он не nil. Все ошибки нужно снабжать префиксом либо с помощью `errors.Wrap`, либо с помощью `fmt.Errorf("do smth: %w", err)`, иначе при возникновении ошибки нельзя будет однозначно идентифицировать, в каком месте она возникла

2022-11-06 01:15 UTC, merged